<?php

/**
 * This file is auto-generated by Boom.
 */

namespace App\HanaEntity;

use W3com\BoomBundle\Annotation\EntityColumnMeta;
use W3com\BoomBundle\Annotation\EntityMeta;
use W3com\BoomBundle\Annotation\EntitySynchronizedData;
use W3com\BoomBundle\Annotation\SynchronizedData;

/**
 * @EntityMeta(read="ods", write="ods", aliasRead="Config")
 */
class Config extends \W3com\BoomBundle\HanaEntity\AbstractEntity
{
	/**
	 * @var string
	 * @EntityColumnMeta(column="Key", description="", type="string", synchro=false, isKey=true)
	 */
	protected $key;

	/**
	 * @var string
	 * @EntityColumnMeta(column="ConfigType", description="", type="string", synchro=false)
	 */
	protected $configType;

	/**
	 * @var string
	 * @EntityColumnMeta(column="Regroupement", description="", type="string", synchro=false)
	 */
	protected $regroupement;

	/**
	 * @var int
	 * @EntityColumnMeta(column="Ordre", description="", type="int", synchro=false, quotes=false)
	 */
	protected $ordre;

	/**
	 * @var string
	 * @EntityColumnMeta(column="Value", description="", type="string", synchro=false)
	 */
	protected $value;


	public function getKey()
	{
		return $this->key;
	}


	public function getConfigType()
	{
		return $this->configType;
	}


	public function getRegroupement()
	{
		return $this->regroupement;
	}


	public function getOrdre()
	{
		return $this->ordre;
	}


	public function getValue()
	{
		return $this->value;
	}
}
